[build-system]
requires = [
    "setuptools>=67",
    "setuptools-scm>=7"
]
build-backend = "setuptools.build_meta"

[project]
name = "typtr"
dynamic = ["version"]
authors = [
    {name = "Niklas Lindström", email = "lindstream@gmail.com"},
]
description = "A transpiler for an idiomatic subset of typed Python into semantically similar object-oriented languages."
license = "ISC"

